codecov:
  disable_default_path_fixes: yes

fixes:
  - "github.com/insomn14/amass/v4/::github.com/insomn14/amass/"

ignore:
  - encode_optype.go
  - ./doc/**/*
  - ./examples/**/*
  - ./images/**/*
  - ./resources/**/*

coverage:
  range: 20..60
  round: up
  precision: 2

comment:
  layout: "reach, diff, files"
  behavior: new
  require_changes: true
  require_base: yes
  require_head: yes
  branches:
    - "develop"
